/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protobuf/chord.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protobuf/chord.pb-c.h"
void   node__init
                     (Node         *message)
{
  static const Node init_value = NODE__INIT;
  *message = init_value;
}
size_t node__get_packed_size
                     (const Node *message)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node__pack
                     (const Node *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node__pack_to_buffer
                     (const Node *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Node *
       node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Node *)
     protobuf_c_message_unpack (&node__descriptor,
                                allocator, len, data);
}
void   node__free_unpacked
                     (Node *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   notify_request__init
                     (NotifyRequest         *message)
{
  static const NotifyRequest init_value = NOTIFY_REQUEST__INIT;
  *message = init_value;
}
size_t notify_request__get_packed_size
                     (const NotifyRequest *message)
{
  assert(message->base.descriptor == &notify_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t notify_request__pack
                     (const NotifyRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &notify_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t notify_request__pack_to_buffer
                     (const NotifyRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &notify_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NotifyRequest *
       notify_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NotifyRequest *)
     protobuf_c_message_unpack (&notify_request__descriptor,
                                allocator, len, data);
}
void   notify_request__free_unpacked
                     (NotifyRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &notify_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   notify_response__init
                     (NotifyResponse         *message)
{
  static const NotifyResponse init_value = NOTIFY_RESPONSE__INIT;
  *message = init_value;
}
size_t notify_response__get_packed_size
                     (const NotifyResponse *message)
{
  assert(message->base.descriptor == &notify_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t notify_response__pack
                     (const NotifyResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &notify_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t notify_response__pack_to_buffer
                     (const NotifyResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &notify_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NotifyResponse *
       notify_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NotifyResponse *)
     protobuf_c_message_unpack (&notify_response__descriptor,
                                allocator, len, data);
}
void   notify_response__free_unpacked
                     (NotifyResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &notify_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   find_successor_request__init
                     (FindSuccessorRequest         *message)
{
  static const FindSuccessorRequest init_value = FIND_SUCCESSOR_REQUEST__INIT;
  *message = init_value;
}
size_t find_successor_request__get_packed_size
                     (const FindSuccessorRequest *message)
{
  assert(message->base.descriptor == &find_successor_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t find_successor_request__pack
                     (const FindSuccessorRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &find_successor_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t find_successor_request__pack_to_buffer
                     (const FindSuccessorRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &find_successor_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FindSuccessorRequest *
       find_successor_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FindSuccessorRequest *)
     protobuf_c_message_unpack (&find_successor_request__descriptor,
                                allocator, len, data);
}
void   find_successor_request__free_unpacked
                     (FindSuccessorRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &find_successor_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   find_successor_response__init
                     (FindSuccessorResponse         *message)
{
  static const FindSuccessorResponse init_value = FIND_SUCCESSOR_RESPONSE__INIT;
  *message = init_value;
}
size_t find_successor_response__get_packed_size
                     (const FindSuccessorResponse *message)
{
  assert(message->base.descriptor == &find_successor_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t find_successor_response__pack
                     (const FindSuccessorResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &find_successor_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t find_successor_response__pack_to_buffer
                     (const FindSuccessorResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &find_successor_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FindSuccessorResponse *
       find_successor_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FindSuccessorResponse *)
     protobuf_c_message_unpack (&find_successor_response__descriptor,
                                allocator, len, data);
}
void   find_successor_response__free_unpacked
                     (FindSuccessorResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &find_successor_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   start_find_successor_request__init
                     (StartFindSuccessorRequest         *message)
{
  static const StartFindSuccessorRequest init_value = START_FIND_SUCCESSOR_REQUEST__INIT;
  *message = init_value;
}
size_t start_find_successor_request__get_packed_size
                     (const StartFindSuccessorRequest *message)
{
  assert(message->base.descriptor == &start_find_successor_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t start_find_successor_request__pack
                     (const StartFindSuccessorRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &start_find_successor_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t start_find_successor_request__pack_to_buffer
                     (const StartFindSuccessorRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &start_find_successor_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StartFindSuccessorRequest *
       start_find_successor_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StartFindSuccessorRequest *)
     protobuf_c_message_unpack (&start_find_successor_request__descriptor,
                                allocator, len, data);
}
void   start_find_successor_request__free_unpacked
                     (StartFindSuccessorRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &start_find_successor_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   start_find_successor_response__init
                     (StartFindSuccessorResponse         *message)
{
  static const StartFindSuccessorResponse init_value = START_FIND_SUCCESSOR_RESPONSE__INIT;
  *message = init_value;
}
size_t start_find_successor_response__get_packed_size
                     (const StartFindSuccessorResponse *message)
{
  assert(message->base.descriptor == &start_find_successor_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t start_find_successor_response__pack
                     (const StartFindSuccessorResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &start_find_successor_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t start_find_successor_response__pack_to_buffer
                     (const StartFindSuccessorResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &start_find_successor_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StartFindSuccessorResponse *
       start_find_successor_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StartFindSuccessorResponse *)
     protobuf_c_message_unpack (&start_find_successor_response__descriptor,
                                allocator, len, data);
}
void   start_find_successor_response__free_unpacked
                     (StartFindSuccessorResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &start_find_successor_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_predecessor_request__init
                     (GetPredecessorRequest         *message)
{
  static const GetPredecessorRequest init_value = GET_PREDECESSOR_REQUEST__INIT;
  *message = init_value;
}
size_t get_predecessor_request__get_packed_size
                     (const GetPredecessorRequest *message)
{
  assert(message->base.descriptor == &get_predecessor_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_predecessor_request__pack
                     (const GetPredecessorRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_predecessor_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_predecessor_request__pack_to_buffer
                     (const GetPredecessorRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_predecessor_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetPredecessorRequest *
       get_predecessor_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetPredecessorRequest *)
     protobuf_c_message_unpack (&get_predecessor_request__descriptor,
                                allocator, len, data);
}
void   get_predecessor_request__free_unpacked
                     (GetPredecessorRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_predecessor_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_predecessor_response__init
                     (GetPredecessorResponse         *message)
{
  static const GetPredecessorResponse init_value = GET_PREDECESSOR_RESPONSE__INIT;
  *message = init_value;
}
size_t get_predecessor_response__get_packed_size
                     (const GetPredecessorResponse *message)
{
  assert(message->base.descriptor == &get_predecessor_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_predecessor_response__pack
                     (const GetPredecessorResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_predecessor_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_predecessor_response__pack_to_buffer
                     (const GetPredecessorResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_predecessor_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetPredecessorResponse *
       get_predecessor_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetPredecessorResponse *)
     protobuf_c_message_unpack (&get_predecessor_response__descriptor,
                                allocator, len, data);
}
void   get_predecessor_response__free_unpacked
                     (GetPredecessorResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_predecessor_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   check_predecessor_request__init
                     (CheckPredecessorRequest         *message)
{
  static const CheckPredecessorRequest init_value = CHECK_PREDECESSOR_REQUEST__INIT;
  *message = init_value;
}
size_t check_predecessor_request__get_packed_size
                     (const CheckPredecessorRequest *message)
{
  assert(message->base.descriptor == &check_predecessor_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t check_predecessor_request__pack
                     (const CheckPredecessorRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &check_predecessor_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t check_predecessor_request__pack_to_buffer
                     (const CheckPredecessorRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &check_predecessor_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CheckPredecessorRequest *
       check_predecessor_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CheckPredecessorRequest *)
     protobuf_c_message_unpack (&check_predecessor_request__descriptor,
                                allocator, len, data);
}
void   check_predecessor_request__free_unpacked
                     (CheckPredecessorRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &check_predecessor_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   check_predecessor_response__init
                     (CheckPredecessorResponse         *message)
{
  static const CheckPredecessorResponse init_value = CHECK_PREDECESSOR_RESPONSE__INIT;
  *message = init_value;
}
size_t check_predecessor_response__get_packed_size
                     (const CheckPredecessorResponse *message)
{
  assert(message->base.descriptor == &check_predecessor_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t check_predecessor_response__pack
                     (const CheckPredecessorResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &check_predecessor_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t check_predecessor_response__pack_to_buffer
                     (const CheckPredecessorResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &check_predecessor_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CheckPredecessorResponse *
       check_predecessor_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CheckPredecessorResponse *)
     protobuf_c_message_unpack (&check_predecessor_response__descriptor,
                                allocator, len, data);
}
void   check_predecessor_response__free_unpacked
                     (CheckPredecessorResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &check_predecessor_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_successor_list_request__init
                     (GetSuccessorListRequest         *message)
{
  static const GetSuccessorListRequest init_value = GET_SUCCESSOR_LIST_REQUEST__INIT;
  *message = init_value;
}
size_t get_successor_list_request__get_packed_size
                     (const GetSuccessorListRequest *message)
{
  assert(message->base.descriptor == &get_successor_list_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_successor_list_request__pack
                     (const GetSuccessorListRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_successor_list_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_successor_list_request__pack_to_buffer
                     (const GetSuccessorListRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_successor_list_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetSuccessorListRequest *
       get_successor_list_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetSuccessorListRequest *)
     protobuf_c_message_unpack (&get_successor_list_request__descriptor,
                                allocator, len, data);
}
void   get_successor_list_request__free_unpacked
                     (GetSuccessorListRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_successor_list_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_successor_list_response__init
                     (GetSuccessorListResponse         *message)
{
  static const GetSuccessorListResponse init_value = GET_SUCCESSOR_LIST_RESPONSE__INIT;
  *message = init_value;
}
size_t get_successor_list_response__get_packed_size
                     (const GetSuccessorListResponse *message)
{
  assert(message->base.descriptor == &get_successor_list_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_successor_list_response__pack
                     (const GetSuccessorListResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_successor_list_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_successor_list_response__pack_to_buffer
                     (const GetSuccessorListResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_successor_list_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetSuccessorListResponse *
       get_successor_list_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetSuccessorListResponse *)
     protobuf_c_message_unpack (&get_successor_list_response__descriptor,
                                allocator, len, data);
}
void   get_successor_list_response__free_unpacked
                     (GetSuccessorListResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_successor_list_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chord_message__init
                     (ChordMessage         *message)
{
  static const ChordMessage init_value = CHORD_MESSAGE__INIT;
  *message = init_value;
}
size_t chord_message__get_packed_size
                     (const ChordMessage *message)
{
  assert(message->base.descriptor == &chord_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chord_message__pack
                     (const ChordMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chord_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chord_message__pack_to_buffer
                     (const ChordMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chord_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChordMessage *
       chord_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChordMessage *)
     protobuf_c_message_unpack (&chord_message__descriptor,
                                allocator, len, data);
}
void   chord_message__free_unpacked
                     (ChordMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chord_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor node__field_descriptors[3] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(Node, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Node, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Node, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned node__field_indices_by_name[] = {
  1,   /* field[1] = address */
  0,   /* field[0] = key */
  2,   /* field[2] = port */
};
static const ProtobufCIntRange node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Node",
  "Node",
  "Node",
  "",
  sizeof(Node),
  3,
  node__field_descriptors,
  node__field_indices_by_name,
  1,  node__number_ranges,
  (ProtobufCMessageInit) node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor notify_request__field_descriptors[1] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(NotifyRequest, node),
    &node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned notify_request__field_indices_by_name[] = {
  0,   /* field[0] = node */
};
static const ProtobufCIntRange notify_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor notify_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NotifyRequest",
  "NotifyRequest",
  "NotifyRequest",
  "",
  sizeof(NotifyRequest),
  1,
  notify_request__field_descriptors,
  notify_request__field_indices_by_name,
  1,  notify_request__number_ranges,
  (ProtobufCMessageInit) notify_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define notify_response__field_descriptors NULL
#define notify_response__field_indices_by_name NULL
#define notify_response__number_ranges NULL
const ProtobufCMessageDescriptor notify_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NotifyResponse",
  "NotifyResponse",
  "NotifyResponse",
  "",
  sizeof(NotifyResponse),
  0,
  notify_response__field_descriptors,
  notify_response__field_indices_by_name,
  0,  notify_response__number_ranges,
  (ProtobufCMessageInit) notify_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor find_successor_request__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(FindSuccessorRequest, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requester",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FindSuccessorRequest, requester),
    &node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned find_successor_request__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = requester */
};
static const ProtobufCIntRange find_successor_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor find_successor_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FindSuccessorRequest",
  "FindSuccessorRequest",
  "FindSuccessorRequest",
  "",
  sizeof(FindSuccessorRequest),
  2,
  find_successor_request__field_descriptors,
  find_successor_request__field_indices_by_name,
  1,  find_successor_request__number_ranges,
  (ProtobufCMessageInit) find_successor_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor find_successor_response__field_descriptors[2] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FindSuccessorResponse, node),
    &node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(FindSuccessorResponse, has_key),
    offsetof(FindSuccessorResponse, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned find_successor_response__field_indices_by_name[] = {
  1,   /* field[1] = key */
  0,   /* field[0] = node */
};
static const ProtobufCIntRange find_successor_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor find_successor_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FindSuccessorResponse",
  "FindSuccessorResponse",
  "FindSuccessorResponse",
  "",
  sizeof(FindSuccessorResponse),
  2,
  find_successor_response__field_descriptors,
  find_successor_response__field_indices_by_name,
  1,  find_successor_response__number_ranges,
  (ProtobufCMessageInit) find_successor_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor start_find_successor_request__field_descriptors[1] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(StartFindSuccessorRequest, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned start_find_successor_request__field_indices_by_name[] = {
  0,   /* field[0] = key */
};
static const ProtobufCIntRange start_find_successor_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor start_find_successor_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StartFindSuccessorRequest",
  "StartFindSuccessorRequest",
  "StartFindSuccessorRequest",
  "",
  sizeof(StartFindSuccessorRequest),
  1,
  start_find_successor_request__field_descriptors,
  start_find_successor_request__field_indices_by_name,
  1,  start_find_successor_request__number_ranges,
  (ProtobufCMessageInit) start_find_successor_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor start_find_successor_response__field_descriptors[1] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StartFindSuccessorResponse, node),
    &node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned start_find_successor_response__field_indices_by_name[] = {
  0,   /* field[0] = node */
};
static const ProtobufCIntRange start_find_successor_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor start_find_successor_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StartFindSuccessorResponse",
  "StartFindSuccessorResponse",
  "StartFindSuccessorResponse",
  "",
  sizeof(StartFindSuccessorResponse),
  1,
  start_find_successor_response__field_descriptors,
  start_find_successor_response__field_indices_by_name,
  1,  start_find_successor_response__number_ranges,
  (ProtobufCMessageInit) start_find_successor_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define get_predecessor_request__field_descriptors NULL
#define get_predecessor_request__field_indices_by_name NULL
#define get_predecessor_request__number_ranges NULL
const ProtobufCMessageDescriptor get_predecessor_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetPredecessorRequest",
  "GetPredecessorRequest",
  "GetPredecessorRequest",
  "",
  sizeof(GetPredecessorRequest),
  0,
  get_predecessor_request__field_descriptors,
  get_predecessor_request__field_indices_by_name,
  0,  get_predecessor_request__number_ranges,
  (ProtobufCMessageInit) get_predecessor_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_predecessor_response__field_descriptors[1] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GetPredecessorResponse, node),
    &node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_predecessor_response__field_indices_by_name[] = {
  0,   /* field[0] = node */
};
static const ProtobufCIntRange get_predecessor_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor get_predecessor_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetPredecessorResponse",
  "GetPredecessorResponse",
  "GetPredecessorResponse",
  "",
  sizeof(GetPredecessorResponse),
  1,
  get_predecessor_response__field_descriptors,
  get_predecessor_response__field_indices_by_name,
  1,  get_predecessor_response__number_ranges,
  (ProtobufCMessageInit) get_predecessor_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define check_predecessor_request__field_descriptors NULL
#define check_predecessor_request__field_indices_by_name NULL
#define check_predecessor_request__number_ranges NULL
const ProtobufCMessageDescriptor check_predecessor_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CheckPredecessorRequest",
  "CheckPredecessorRequest",
  "CheckPredecessorRequest",
  "",
  sizeof(CheckPredecessorRequest),
  0,
  check_predecessor_request__field_descriptors,
  check_predecessor_request__field_indices_by_name,
  0,  check_predecessor_request__number_ranges,
  (ProtobufCMessageInit) check_predecessor_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define check_predecessor_response__field_descriptors NULL
#define check_predecessor_response__field_indices_by_name NULL
#define check_predecessor_response__number_ranges NULL
const ProtobufCMessageDescriptor check_predecessor_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CheckPredecessorResponse",
  "CheckPredecessorResponse",
  "CheckPredecessorResponse",
  "",
  sizeof(CheckPredecessorResponse),
  0,
  check_predecessor_response__field_descriptors,
  check_predecessor_response__field_indices_by_name,
  0,  check_predecessor_response__number_ranges,
  (ProtobufCMessageInit) check_predecessor_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define get_successor_list_request__field_descriptors NULL
#define get_successor_list_request__field_indices_by_name NULL
#define get_successor_list_request__number_ranges NULL
const ProtobufCMessageDescriptor get_successor_list_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetSuccessorListRequest",
  "GetSuccessorListRequest",
  "GetSuccessorListRequest",
  "",
  sizeof(GetSuccessorListRequest),
  0,
  get_successor_list_request__field_descriptors,
  get_successor_list_request__field_indices_by_name,
  0,  get_successor_list_request__number_ranges,
  (ProtobufCMessageInit) get_successor_list_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_successor_list_response__field_descriptors[1] =
{
  {
    "successors",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GetSuccessorListResponse, n_successors),
    offsetof(GetSuccessorListResponse, successors),
    &node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_successor_list_response__field_indices_by_name[] = {
  0,   /* field[0] = successors */
};
static const ProtobufCIntRange get_successor_list_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor get_successor_list_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetSuccessorListResponse",
  "GetSuccessorListResponse",
  "GetSuccessorListResponse",
  "",
  sizeof(GetSuccessorListResponse),
  1,
  get_successor_list_response__field_descriptors,
  get_successor_list_response__field_indices_by_name,
  1,  get_successor_list_response__number_ranges,
  (ProtobufCMessageInit) get_successor_list_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t chord_message__version__default_value = 417u;
static const ProtobufCFieldDescriptor chord_message__field_descriptors[14] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ChordMessage, version),
    NULL,
    &chord_message__version__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notify_request",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, notify_request),
    &notify_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notify_response",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, notify_response),
    &notify_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "find_successor_request",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, find_successor_request),
    &find_successor_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "find_successor_response",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, find_successor_response),
    &find_successor_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_predecessor_request",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, get_predecessor_request),
    &get_predecessor_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_predecessor_response",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, get_predecessor_response),
    &get_predecessor_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "check_predecessor_request",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, check_predecessor_request),
    &check_predecessor_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "check_predecessor_response",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, check_predecessor_response),
    &check_predecessor_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_successor_list_request",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, get_successor_list_request),
    &get_successor_list_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_successor_list_response",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, get_successor_list_response),
    &get_successor_list_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "query_id",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ChordMessage, has_query_id),
    offsetof(ChordMessage, query_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_find_successor_request",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, start_find_successor_request),
    &start_find_successor_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_find_successor_response",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, start_find_successor_response),
    &start_find_successor_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chord_message__field_indices_by_name[] = {
  7,   /* field[7] = check_predecessor_request */
  8,   /* field[8] = check_predecessor_response */
  3,   /* field[3] = find_successor_request */
  4,   /* field[4] = find_successor_response */
  5,   /* field[5] = get_predecessor_request */
  6,   /* field[6] = get_predecessor_response */
  9,   /* field[9] = get_successor_list_request */
  10,   /* field[10] = get_successor_list_response */
  1,   /* field[1] = notify_request */
  2,   /* field[2] = notify_response */
  11,   /* field[11] = query_id */
  12,   /* field[12] = start_find_successor_request */
  13,   /* field[13] = start_find_successor_response */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange chord_message__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 14, 11 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor chord_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ChordMessage",
  "ChordMessage",
  "ChordMessage",
  "",
  sizeof(ChordMessage),
  14,
  chord_message__field_descriptors,
  chord_message__field_indices_by_name,
  2,  chord_message__number_ranges,
  (ProtobufCMessageInit) chord_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
